id: fhir.example
canonical: http://example.org
name: ExampleIG
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2025+
releaseLabel: ci-build
FSHOnly: false
menu:
  Home: index.html
  Artifacts: artifacts.html
instanceOptions:
  manualSliceOrdering: true
publisher:
  name: Example Publisher
  url: http://example.org/example-publisher
