name: run-sushi-and-ig-publisher
on:
  workflow_call:
jobs:
  run-sushi-and-ig-publisher:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js for SUSHI
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install SUSHI
        run: npm install -g fsh-sushi

      - name: Generate Resources with SUSHI
        working-directory: ExampleIG
        run: sushi .

      - name: Download the IG Publisher
        run: |
          curl -L https://github.com/HL7/fhir-ig-publisher/releases/latest/download/publisher.jar -o publisher.jar

      - name: Run the IG Publisher
        run: |
          java -jar publisher.jar -ig ./ExampleIG/ig.ini -no-sushi

      - name: Persist Artifacts
        uses: actions/upload-artifact@v4.6.0
        with:
          name: output
          path: ./ExampleIG/output
